[Max Price] - Prevent buying scalper stuff
Hari-Nagarajan/nvidia-bot pull request #275
Opened 2020-11-04 23:43 UTC by pr1ntr

Just adds a reserve price to the amz config.

2020-11-05 00:04 UTC, worst-mod-confirmed requested changes
Fix line 195.

2020-11-05 14:03 UTC, DakkJaniels commented
Suggestion: Instead of adding smile to url template, just remove www from the url template and that needs to be included if you are using the non-smile amazon site. As written, I think this would break amazon for non US users.

2020-11-05 14:04 UTC, DakkJaniels commented on stores/amazon.py
> +    "CART_URL": "https://smile.{domain}/gp/aws/cart/add.html",
delete "smile."

2020-11-05 14:05 UTC, DakkJaniels commented on amazon_config.template_json
> +  "amazon_website": "amazon.co.uk",
add "www." or "smile.". I don't think "smile.amazon.*" exists for all language versions of the amazon site.

2020-11-05 14:08 UTC, DakkJaniels commented on README.md
> +  "amazon_website": "amazon.com",
```suggestion
  "amazon_website": "www.amazon.com",
```

2020-11-05 14:13 UTC, DakkJaniels requested changes
Modified to URLs to remove "www." to make it easier to switch to smile.amazon.*

2020-11-05 14:13 UTC, DakkJaniels commented on stores/amazon.py
>      "BASE_URL": "https://www.{domain}/",
```suggestion
    "BASE_URL": "https://{domain}/",
```

2020-11-05 14:13 UTC, DakkJaniels commented on README.md
> +  "amazon_website": "amazon.com",
```suggestion
  "amazon_website": "www.amazon.com",
```

2020-11-05 14:13 UTC, DakkJaniels commented on amazon_config.template_json
> +  "amazon_website": "amazon.co.uk",
```suggestion
  "amazon_website": "www.amazon.co.uk",
```

2020-11-05 14:13 UTC, DakkJaniels commented on stores/amazon.py
> +    "CART_URL": "https://smile.{domain}/gp/aws/cart/add.html",
```suggestion
    "CART_URL": "https://{domain}/gp/aws/cart/add.html",
```

2020-11-05 14:13 UTC, DakkJaniels commented on stores/amazon.py
>  CHECKOUT_URL = "https://www.{domain}/gp/cart/desktop/go-to-checkout.html/ref=ox_sc_proceed?partialCheckoutCart=1&isToBeGiftWrappedBefore=0&proceedToRetailCheckout=Proceed+to+checkout&proceedToCheckou
```suggestion
CHECKOUT_URL = "https://{domain}/gp/cart/desktop/go-to-checkout.html/ref=ox_sc_proceed?partialCheckoutCart=1&isToBeGiftWrappedBefore=0&proceedToRetailCheckout=Proceed+to+checkout&proceedToCheckout=1&cartInitiateId={cart_id}"
```

2020-11-05 14:13 UTC, DakkJaniels commented on stores/amazon.py
> +                log.info("Shit costs too much fuck that")
```suggestion
                log.info("No stock available under reserve price")
```

2020-11-07 00:19 UTC, DakkJaniels commented on stores/amazon.py
> +    "AmazonSmile Thanks You"
```suggestion
    "AmazonSmile Thanks You",
```

2020-11-07 21:59 UTC, worst-mod-confirmed submitted a review, later dismissed

2020-11-07 22:06 UTC, DakkJaniels commented
Make sure the comma gets added before this is pulled in. https://github.com/Hari-Nagarajan/nvidia-bot/pull/275#discussion_r519065730

2020-11-07 22:21 UTC, worst-mod-confirmed approved these changes

2020-11-09 21:19 UTC, DakkJaniels commented on stores/amazon.py
> +            price = float(price_element[0].text[1:])
Sorry, forgot to include this before. This fails if the price has a comma in it. Could use package that has locale, which would be more robust, but for US (or anywhere that uses comma for separating digit groupings):
```suggestion

            price_str = price_element[0].text[1:]
            price = float(str_price.replace(',',''))
```

2020-11-13 22:37 UTC, closed without merging

2020-11-13 22:41 UTC, DakkJaniels commented
I think this has been implemented in the master now.